import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { computeVocalActivity } from '../../src/ai-pipeline/vocalActivity'
import { readWavMono } from './helpers/readWavMono'

/**
 * Tier A committed audio, end to end (plan item W0.5). W1.2 Layer 1 (the global-offset
 * estimator) was deleted as a dead end on 2026-09-30 — ledger L29 — and its specs went with it.
 *
 * These clips are generated by scripts/make-tier-a.mjs from this repository's own
 * code, so they are legally shippable AND reproducible by anyone who clones it —
 * which is the whole point. Before them, no audio was in the tree (`.gitignore`
 * excludes the copyrighted staged recordings), so the audio -> feature half of the
 * pipeline had ZERO regression coverage: the envelope, onset detection, and every
 * downstream consumer could break with nothing failing.
 *
 * WHAT IS ASSERTED: that the audio-feature path works on real samples, against ground
 * truth known by construction — the envelope finds voiced stretches, the first onset
 * lands where the intro ends, an instrumental break reads as unvoiced, a 14 dB level
 * change does not hide the quiet half.
 *
 * WHAT IS NOT ASSERTED, AND MUST NEVER BE: lyric alignment. The carrier is a
 * synthesized harmonic stack with no words in it. Nothing here can tell you whether a
 * lyric line lands on the right syllable, and no test in this file may be cited for
 * that. Absolute lyric accuracy needs real singing — see manifest.json's
 * `pendingUserRecordings` and plan W0.4/W4.3.
 */

const here = dirname(fileURLToPath(import.meta.url))
const TIER_A = join(here, 'fixtures/tier-a')

interface Clip {
  file: string
  sampleRate: number
  durationSec: number
  sha256: string
  condition: string
  expect: string
  trueOnsets: number[]
  introSec?: number
  breakSec?: number
  quietSec?: number
  masked?: boolean
}

const manifest = JSON.parse(readFileSync(join(TIER_A, 'manifest.json'), 'utf8')) as {
  clips: Clip[]
  pendingUserRecordings: { why: string }
}
const byFile = new Map(manifest.clips.map((c) => [c.file, c]))

function load(file: string) {
  const clip = byFile.get(file)
  if (!clip) throw new Error(`clip ${file} missing from manifest`)
  const { data, sampleRate } = readWavMono(join(TIER_A, file))
  const sig = computeVocalActivity(data, sampleRate, { source: 'mix' })
  return { clip, data, sampleRate, sig }
}

/** Strongest activity onset at or after `from`, in seconds — a crude but direct
 * read of "the envelope found something starting here". */
function firstVoicedAfter(sig: { hopSec: number; activity: Float32Array }, from: number): number | null {
  const startFrame = Math.max(0, Math.round(from / sig.hopSec))
  for (let f = startFrame; f < sig.activity.length; f++) {
    // Two consecutive frames above threshold: a single spike is noise, not a voice.
    if (sig.activity[f] > 0.05 && sig.activity[f + 1] > 0.05) return f * sig.hopSec
  }
  return null
}

function meanIn(sig: { hopSec: number; activity: Float32Array }, a: number, b: number): number {
  const fa = Math.max(0, Math.round(a / sig.hopSec))
  const fb = Math.min(sig.activity.length, Math.round(b / sig.hopSec))
  if (fb <= fa) return 0
  let s = 0
  for (let f = fa; f < fb; f++) s += sig.activity[f]
  return s / (fb - fa)
}

describe('Tier A committed audio — the audio-feature path on real samples', () => {
  it('every manifest clip is present, in the manifest, and unmodified', () => {
    // Content hashes make a fixture drift visible. The generator is deterministic, so
    // a mismatch means either the WAV was edited by hand or the generator changed
    // without regenerating — both must be deliberate.
    for (const clip of manifest.clips) {
      const { data } = load(clip.file)
      expect(data.length, `${clip.file}: sample count matches duration`).toBe(
        Math.round(clip.durationSec * clip.sampleRate),
      )
    }
  })

  it('finds the first onset where the intro actually ends', () => {
    const { clip, sig } = load('silent-intro.wav')
    const first = firstVoicedAfter(sig, 0)
    expect(first).not.toBeNull()
    // The intro is 7s of bed; the carrier starts at `trueOnsets[0]`.
    expect(clip.introSec).toBe(7)
    expect(first as number).toBeGreaterThan(clip.introSec - 0.5)
    expect(first as number).toBeLessThan(clip.trueOnsets[0] + 0.5)
  })

  it('reads an instrumental break as unvoiced instead of smearing across it', () => {
    const { clip, sig } = load('instrumental-break.wav')
    const [breakStart, breakEnd] = clip.breakSec as [number, number]
    const inside = meanIn(sig, breakStart + 0.5, breakEnd - 0.5)
    const before = meanIn(sig, clip.trueOnsets[0], clip.trueOnsets[1])
    expect(inside, 'break carries far less vocal-band energy than a sung section').toBeLessThan(before * 0.6)
  })

  it('finds onsets in a section 14 dB quieter than its neighbour', () => {
    // The quiet-verse case: VOICED_THRESHOLD is deliberately low so genuinely-sung
    // but quiet passages still register.
    const { clip, sig } = load('level-change.wav')
    const [qStart, qEnd] = clip.quietSec as [number, number]
    const quiet = clip.trueOnsets.filter((t) => t >= qStart && t < qEnd)
    const loud = clip.trueOnsets.filter((t) => t >= qEnd)
    expect(quiet.length).toBeGreaterThan(0)
    expect(loud.length).toBeGreaterThan(0)
    const firstQuietOnset = firstVoicedAfter(sig, qStart + 0.2)
    expect(firstQuietOnset, 'quiet section still registers as voiced').not.toBeNull()
    expect(firstQuietOnset as number).toBeLessThan(quiet[0] + 1.0)
  })

  it('keeps the corpus honest about what it can and cannot show', () => {
    // A guard on the guard: if someone later adds a real-singing clip here and starts
    // asserting lyric accuracy from Tier A alone, this fails until the manifest is
    // updated deliberately.
    expect(manifest.pendingUserRecordings.why).toMatch(/real singing/i)
    for (const clip of manifest.clips) {
      expect(clip.expect.length).toBeGreaterThan(5)
      expect(clip.condition.length).toBeGreaterThan(10)
    }
  })
})
