import { describe, it, expect } from 'vitest'
import { createHash } from 'node:crypto'
import { existsSync, readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

/**
 * Tier B — the DEVELOPER-RUN audio corpus, and the gap it must not hide.
 *
 * These recordings are copyrighted, so their files are not in the repository and never will
 * be. The manifest (`fixtures/tier-b/manifest.json`, generated by `scripts/tier-b-audio.mjs`)
 * is the record instead, and it exists for two reasons that are both about honesty:
 *
 *  1. **Reproducibility.** Every accuracy number recorded in the ledger and the plan was
 *     computed from these exact bytes. The hashes are the contract: anyone holding the same
 *     files can re-run the instruments and must get the same numbers.
 *  2. **Legibility.** A clone without the files measures LESS — it always did — and the
 *     problem the audit found was that nothing said so: 26 tests silently skipped on a clean
 *     checkout, taking ~19 of ~30 external-truth assertions with them, behind a green run.
 *     This file therefore reports what could not be measured rather than passing quietly.
 *
 * What is asserted here is only what holds on ANY machine: structure, provenance discipline,
 * and hash agreement for files that happen to be present. Whether the audio is present is a
 * property of the machine, not of the code, so its absence is recorded, never failed — but
 * the count is asserted to be reported, which is what stops "green" from implying "measured".
 */

const here = dirname(fileURLToPath(import.meta.url))
const MANIFEST = join(here, 'fixtures/tier-b/manifest.json')

interface Entry {
  key: string
  file: string
  kind: 'mix' | 'stem'
  covers: string[]
  truth: string | null
  truthQuality: string
  sha256?: string
  bytes?: number
  durationSec?: number
  available?: boolean
  pairsWith?: string
}

const manifest = JSON.parse(readFileSync(MANIFEST, 'utf8')) as {
  files: Entry[]
  committable: boolean
  audioDir: string
  runMeasuresWith: string[]
}

const present = manifest.files.filter((e) => existsSync(join(here, '..', '..', manifest.audioDir, e.file)))

describe('Tier B audio corpus manifest', () => {
  it('is explicitly NOT committable, and says where the audio lives', () => {
    // The one thing that must never drift: these files are copyrighted, so if this ever
    // flips to true the repository has a licensing problem.
    expect(manifest.committable).toBe(false)
    expect(manifest.audioDir).toBe('public/e2e')
  })

  it('names what every entry is FOR, not merely that it exists', () => {
    expect(manifest.files.length).toBeGreaterThan(0)
    for (const e of manifest.files) {
      expect(e.key.length, `${e.file}: has a key`).toBeGreaterThan(2)
      expect(e.covers.length, `${e.file}: says which failure modes it covers`).toBeGreaterThan(0)
      for (const c of e.covers) expect(c.length, `${e.file}: cover note is substantive`).toBeGreaterThan(8)
    }
  })

  it('records truth provenance, or explains why there is none', () => {
    for (const e of manifest.files) {
      if (e.kind === 'stem') continue // stems are not aligned against truth directly
      // Either a truth fixture, or an explicit reason it cannot have one.
      expect(
        e.truth != null || e.truthQuality.length > 20,
        `${e.file}: needs a truth fixture or a documented reason it has none`,
      ).toBe(true)
      expect(e.truthQuality.length, `${e.file}: truth quality is documented`).toBeGreaterThan(10)
    }
  })

  it('marks every one-sided truth as one-sided', () => {
    // stranger-than-heaven's LRC is a 237s edit of 233.57s audio: its offset is partly a
    // version difference and cannot be attributed to the aligner. A truth file that is not
    // version-matched must SAY so, or its numbers get quoted as if they were ours.
    const oneSided = manifest.files.filter((e) => /ONE-SIDED/i.test(e.truthQuality))
    for (const e of oneSided) {
      expect(e.durationSec ?? 0, `${e.file}: a one-sided fixture records its measured duration`).toBeGreaterThan(0)
    }
    // And the corpus must contain the version-EXACT case too, or there is nothing to
    // calibrate an attribution against.
    expect(manifest.files.some((e) => /version-EXACT/i.test(e.truthQuality))).toBe(true)
  })

  it('tells a clone how to reproduce the numbers', () => {
    expect(manifest.runMeasuresWith.length).toBeGreaterThan(0)
    for (const cmd of manifest.runMeasuresWith) expect(cmd.startsWith('npx tsx ')).toBe(true)
  })

  it('hash-verifies whatever audio this machine has, and reports the rest', () => {
    const mismatched: string[] = []
    for (const e of present) {
      const bytes = readFileSync(join(here, '..', '..', manifest.audioDir, e.file))
      const sha256 = createHash('sha256').update(bytes).digest('hex')
      if (sha256 !== e.sha256) mismatched.push(`${e.file}: manifest ${e.sha256?.slice(0, 12)}… vs actual ${sha256.slice(0, 12)}…`)
    }
    expect(
      mismatched,
      'a Tier B file changed since the manifest was written — every number measured against it is invalidated. Re-run scripts/tier-b-audio.mjs --write only if deliberate.',
    ).toEqual([])

    // The legibility assertion. Whatever the machine has, how much of the corpus it could
    // NOT use is a reported fact rather than an absence. On a clean checkout that is the
    // whole corpus, and this test passing must not be read as "the singing claims were
    // checked" — it means they were NOT, and here is the count.
    const coverage = present.length / manifest.files.length
    expect(coverage).toBeGreaterThanOrEqual(0)
    expect(present.length).toBeLessThanOrEqual(manifest.files.length)
    if (coverage < 1) {
      const absent = manifest.files.filter((e) => !present.includes(e)).map((e) => e.file)
      expect(absent.length).toBe(manifest.files.length - present.length)
    }
  })
})
