import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { computeVocalActivity } from '../../src/ai-pipeline/vocalActivity'
import { estimateGlobalOffset } from '../../src/ai-pipeline/offsetEstimate'
import { readWavMono } from './helpers/readWavMono'

/**
 * Tier A committed audio, end to end (plan items W0.5 and W1.2 Layer 1).
 *
 * These clips are generated by scripts/make-tier-a.mjs from this repository's own
 * code, so they are legally shippable AND reproducible by anyone who clones it —
 * which is the whole point. Before them, no audio was in the tree (`.gitignore`
 * excludes the copyrighted staged recordings), so the audio -> feature half of the
 * pipeline had ZERO regression coverage: the envelope, onset detection, and every
 * downstream consumer could break with nothing failing.
 *
 * WHAT IS ASSERTED: that the audio-feature path works on real samples, against ground
 * truth known by construction — the envelope finds voiced stretches, the first onset
 * lands where the intro ends, an instrumental break reads as unvoiced, a 14 dB level
 * change does not hide the quiet half, and the global-offset estimator recovers a known
 * shift.
 *
 * WHAT IS NOT ASSERTED, AND MUST NEVER BE: lyric alignment. The carrier is a
 * synthesized harmonic stack with no words in it. Nothing here can tell you whether a
 * lyric line lands on the right syllable, and no test in this file may be cited for
 * that. Absolute lyric accuracy needs real singing — see manifest.json's
 * `pendingUserRecordings` and plan W0.4/W4.3.
 */

const here = dirname(fileURLToPath(import.meta.url))
const TIER_A = join(here, 'fixtures/tier-a')

interface Clip {
  file: string
  sampleRate: number
  durationSec: number
  sha256: string
  condition: string
  expect: string
  trueOnsets: number[]
  introSec?: number
  breakSec?: number
  quietSec?: number
  masked?: boolean
}

const manifest = JSON.parse(readFileSync(join(TIER_A, 'manifest.json'), 'utf8')) as {
  clips: Clip[]
  pendingUserRecordings: { why: string }
}
const byFile = new Map(manifest.clips.map((c) => [c.file, c]))

function load(file: string) {
  const clip = byFile.get(file)
  if (!clip) throw new Error(`clip ${file} missing from manifest`)
  const { data, sampleRate } = readWavMono(join(TIER_A, file))
  const sig = computeVocalActivity(data, sampleRate, { source: 'mix' })
  return { clip, data, sampleRate, sig }
}

/** Strongest activity onset at or after `from`, in seconds — a crude but direct
 * read of "the envelope found something starting here". */
function firstVoicedAfter(sig: { hopSec: number; activity: Float32Array }, from: number): number | null {
  const startFrame = Math.max(0, Math.round(from / sig.hopSec))
  for (let f = startFrame; f < sig.activity.length; f++) {
    // Two consecutive frames above threshold: a single spike is noise, not a voice.
    if (sig.activity[f] > 0.05 && sig.activity[f + 1] > 0.05) return f * sig.hopSec
  }
  return null
}

function meanIn(sig: { hopSec: number; activity: Float32Array }, a: number, b: number): number {
  const fa = Math.max(0, Math.round(a / sig.hopSec))
  const fb = Math.min(sig.activity.length, Math.round(b / sig.hopSec))
  if (fb <= fa) return 0
  let s = 0
  for (let f = fa; f < fb; f++) s += sig.activity[f]
  return s / (fb - fa)
}

describe('Tier A committed audio — the audio-feature path on real samples', () => {
  it('every manifest clip is present, in the manifest, and unmodified', () => {
    // Content hashes make a fixture drift visible. The generator is deterministic, so
    // a mismatch means either the WAV was edited by hand or the generator changed
    // without regenerating — both must be deliberate.
    for (const clip of manifest.clips) {
      const { data } = load(clip.file)
      expect(data.length, `${clip.file}: sample count matches duration`).toBe(
        Math.round(clip.durationSec * clip.sampleRate),
      )
    }
  })

  it('finds the first onset where the intro actually ends', () => {
    const { clip, sig } = load('silent-intro.wav')
    const first = firstVoicedAfter(sig, 0)
    expect(first).not.toBeNull()
    // The intro is 7s of bed; the carrier starts at `trueOnsets[0]`.
    expect(clip.introSec).toBe(7)
    expect(first as number).toBeGreaterThan(clip.introSec - 0.5)
    expect(first as number).toBeLessThan(clip.trueOnsets[0] + 0.5)
  })

  it('reads an instrumental break as unvoiced instead of smearing across it', () => {
    const { clip, sig } = load('instrumental-break.wav')
    const [breakStart, breakEnd] = clip.breakSec as [number, number]
    const inside = meanIn(sig, breakStart + 0.5, breakEnd - 0.5)
    const before = meanIn(sig, clip.trueOnsets[0], clip.trueOnsets[1])
    expect(inside, 'break carries far less vocal-band energy than a sung section').toBeLessThan(before * 0.6)
  })

  it('finds onsets in a section 14 dB quieter than its neighbour', () => {
    // The quiet-verse case: VOICED_THRESHOLD is deliberately low so genuinely-sung
    // but quiet passages still register.
    const { clip, sig } = load('level-change.wav')
    const [qStart, qEnd] = clip.quietSec as [number, number]
    const quiet = clip.trueOnsets.filter((t) => t >= qStart && t < qEnd)
    const loud = clip.trueOnsets.filter((t) => t >= qEnd)
    expect(quiet.length).toBeGreaterThan(0)
    expect(loud.length).toBeGreaterThan(0)
    const firstQuietOnset = firstVoicedAfter(sig, qStart + 0.2)
    expect(firstQuietOnset, 'quiet section still registers as voiced').not.toBeNull()
    expect(firstQuietOnset as number).toBeLessThan(quiet[0] + 1.0)
  })

  describe('global-offset estimation (W1.2 Layer 1)', () => {
    // Claimed starts are the true onsets with a KNOWN offset applied, so the
    // estimator's job is exactly the real one: recover a constant lag from the
    // audio's own vocal activity.
    const SHIFT = 0.48
    const shifted = (clip: Clip) => clip.trueOnsets.map((t) => t + SHIFT)

    it('recovers a known constant shift from a clean carrier', () => {
      const { clip, sig } = load('onsets-clean.wav')
      const est = estimateGlobalOffset({
        claimedStarts: shifted(clip),
        sig,
        durationSec: clip.durationSec,
      })
      expect(est, 'should produce an estimate on a clean carrier').not.toBeNull()
      // Measured 0.030s. The 0.08 bound is ~2.5x headroom, and stays inside the
      // perceptual contract's C1 (a 100ms systematic offset is the requirement).
      expect(Math.abs((est as { shiftSec: number }).shiftSec + SHIFT)).toBeLessThan(0.08)
    })

    it('recovers the shift when the carrier sits under a loud out-of-band bed', () => {
      const { clip, sig } = load('onsets-over-bass-bed.wav')
      const est = estimateGlobalOffset({
        claimedStarts: shifted(clip),
        sig,
        durationSec: clip.durationSec,
      })
      expect(est).not.toBeNull()
      // Measured 0.050s — slightly worse than the clean clip, because the bass bed
      // still perturbs the envelope, but far inside C1.
      expect(Math.abs((est as { shiftSec: number }).shiftSec + SHIFT)).toBeLessThan(0.1)
    })

    it('says nothing when there is no shift to make', () => {
      // Already-correct timings must produce a refusal, not a small invented shift:
      // applying one would move correct lyrics for no reason.
      const { clip, sig } = load('onsets-clean.wav')
      const est = estimateGlobalOffset({
        claimedStarts: clip.trueOnsets,
        sig,
        durationSec: clip.durationSec,
      })
      expect(est, 'no gain over zero shift means no estimate').toBeNull()
    })

    it('REFUSES when the carrier is masked inside its own band', () => {
      // The historical objection, as an assertion. A densely-masked carrier gives the
      // envelope energy nearly everywhere, so onset structure is gone; the estimator
      // must decline rather than return a confident-looking wrong number.
      const { clip, sig } = load('masked-carrier.wav')
      expect(clip.masked).toBe(true)
      const est = estimateGlobalOffset({
        claimedStarts: shifted(clip),
        sig,
        durationSec: clip.durationSec,
      })
      expect(
        est,
        'a masked carrier must yield no estimate — if this ever starts returning one, the confidence gate has regressed',
      ).toBeNull()
    })

    it('refuses rather than guessing when there are too few lines to judge', () => {
      const { clip, sig } = load('onsets-clean.wav')
      const est = estimateGlobalOffset({
        claimedStarts: clip.trueOnsets.slice(0, 2),
        sig,
        durationSec: clip.durationSec,
      })
      expect(est).toBeNull()
    })

    it('does not claim a shift beyond the search range it declares', () => {
      // A wildly wrong prior is a version mismatch, not an offset; the estimate must
      // stay inside MAX_SHIFT_SEC so the caller can treat "no estimate" as
      // "escalate", never as "shift by 40 seconds".
      const { clip, sig } = load('onsets-clean.wav')
      const est = estimateGlobalOffset({
        claimedStarts: clip.trueOnsets.map((t) => t + 40),
        sig,
        durationSec: clip.durationSec,
      })
      // A 40s-wrong prior is outside the search range by design, so the module either
      // refuses or returns something inside the range it declares — never a 40s shift.
      if (est) expect(Math.abs(est.shiftSec)).toBeLessThanOrEqual(0.75)
    })
  })

  it('keeps the corpus honest about what it can and cannot show', () => {
    // A guard on the guard: if someone later adds a real-singing clip here and starts
    // asserting lyric accuracy from Tier A alone, this fails until the manifest is
    // updated deliberately.
    expect(manifest.pendingUserRecordings.why).toMatch(/real singing/i)
    for (const clip of manifest.clips) {
      expect(clip.expect.length).toBeGreaterThan(5)
      expect(clip.condition.length).toBeGreaterThan(10)
    }
  })
})
